### ISSUE TITLE
The operator does not have common structure

### ISSUE THREAD

**Issue by jsafrane** [JiaoDean/alibaba-cloud-csi-driver-operator#1]
All other CSI driver operators in OCP have the same directory structure, with `assets/` and `cmd/` directories and Dockerfile in the root dir. Please follow the same structure, so all operators look the same and are consistent. Check https://github.com/openshift/gcp-pd-csi-driver-operator as a good example.

**Comment by bertinatto** [comment]
Nit: please also add the Makefile.

**Comment by jsafrane** [comment]
This seems to be fixed now.
